image: surangagamage/deployer-bitbucket-pipeline
pipelines:
  custom:
    prod-deploy-unlock:
      - step:
          script:
            # Places the default bitbucket id in the predictable location to make life easier for all the
            # subsequent commands (rsync etc).
            - ln -s /opt/atlassian/pipelines/agent/data/id_rsa ~/.ssh/id_rsa
            - cd .heavyd && composer install --no-interaction --no-progress --prefer-dist --no-suggest && cd ..
            - ./.heavyd/vendor/bin/phing property:write-full
            - ./.heavyd/vendor/bin/dep deploy:unlock prod -vv
    prod-deploy-code:
      - step:
          script:
            # Places the default bitbucket id in the predictable location to make life easier for all the
            # subsequent commands (rsync etc).
            - ln -s /opt/atlassian/pipelines/agent/data/id_rsa ~/.ssh/id_rsa
            - cd .heavyd && composer install --no-interaction --no-progress --prefer-dist --no-suggest && cd ..
            - ./.heavyd/vendor/bin/phing property:write-full
            - ./.heavyd/vendor/bin/dep deploy:code prod -vv
    prod-deploy-full:
      - step:
          script:
            # Places the default bitbucket id in the predictable location to make life easier for all the
            # subsequent commands (rsync etc).
            - ln -s /opt/atlassian/pipelines/agent/data/id_rsa ~/.ssh/id_rsa
            - cd .heavyd && composer install --no-interaction --no-progress --prefer-dist --no-suggest && cd ..
            - ./.heavyd/vendor/bin/phing property:write-full
            - ./.heavyd/vendor/bin/dep deploy:full prod -vv
  branches:
    master:
      - step:
          script:
            # Places the default bitbucket id in the predictable location to make life easier for all the
            # subsequent commands (rsync etc).
            - cd .heavyd && composer install --no-interaction --no-progress --prefer-dist --no-suggest && cd ..
            - ./.heavyd/vendor/bin/phing property:write-full
            - ./.heavyd/vendor/bin/dep deploy:full prod -vv
  tags:
    '*':
      - step:
          script:
            # Places the default bitbucket id in the predictable location to make life easier for all the
            # subsequent commands (rsync etc).
            - ln -s /opt/atlassian/pipelines/agent/data/id_rsa ~/.ssh/id_rsa
            - cd .heavyd && composer install --no-interaction --no-progress --prefer-dist --no-suggest && cd ..
            - ./.heavyd/vendor/bin/phing property:write-full
            - ./.heavyd/vendor/bin/dep deploy:full prod -vv
